server:
  port: "8081"
  api_key: "secret123"

database:
  driver: "mysql" # mysql or sqlite
  # SQLite config
  file: "blog.db"
  # MySQL config
  host: "10.21.32.13"
  port: "3306"
  user: "root"
  password: "12345678"
  dbname: "openblog"
